package sop_corba;


/**
* sop_corba/GestionNotificacionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 20 de diciembre de 2020 10:47:51 PM COT
*/

abstract public class GestionNotificacionHelper
{
  private static String  _id = "IDL:sop_corba/GestionNotificacion:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.GestionNotificacion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.GestionNotificacion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sop_corba.GestionNotificacionHelper.id (), "GestionNotificacion");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.GestionNotificacion read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionNotificacionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.GestionNotificacion value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sop_corba.GestionNotificacion narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.GestionNotificacion)
      return (sop_corba.GestionNotificacion)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._GestionNotificacionStub stub = new sop_corba._GestionNotificacionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sop_corba.GestionNotificacion unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.GestionNotificacion)
      return (sop_corba.GestionNotificacion)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._GestionNotificacionStub stub = new sop_corba._GestionNotificacionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
