package sop_corba;


/**
* sop_corba/GestionNotificacionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 20 de diciembre de 2020 10:47:51 PM COT
*/

public interface GestionNotificacionOperations 
{
  boolean enviarNotificacionPedido (sop_corba.GestionNotificacionPackage.notificacionDTO objNotificacion);
} // interface GestionNotificacionOperations
