package sop_corba;

/**
* sop_corba/GestionNotificacionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 20 de diciembre de 2020 10:47:51 PM COT
*/

public final class GestionNotificacionHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionNotificacion value = null;

  public GestionNotificacionHolder ()
  {
  }

  public GestionNotificacionHolder (sop_corba.GestionNotificacion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionNotificacionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionNotificacionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionNotificacionHelper.type ();
  }

}
