package sop_corba.GestionNotificacionPackage;


/**
* sop_corba/GestionNotificacionPackage/notificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 20 de diciembre de 2020 10:47:51 PM COT
*/

public final class notificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int numeroMesa = (int)0;
  public sop_corba.GestionNotificacionPackage.hamburguesaNotificacionDTO listaHamburguesas[] = null;

  public notificacionDTO ()
  {
  } // ctor

  public notificacionDTO (int _numeroMesa, sop_corba.GestionNotificacionPackage.hamburguesaNotificacionDTO[] _listaHamburguesas)
  {
    numeroMesa = _numeroMesa;
    listaHamburguesas = _listaHamburguesas;
  } // ctor

} // class notificacionDTO
